### ISSUE TITLE
[BUG] Conversion does not remove optional cue identifiers in a vtt cue block (results in doubled sequence numbering)

### ISSUE THREAD

**Issue by e-d-n-a** [0um/vtt-to-srt.py#24]
## Expected Behavior
In the WebVTT format each [cue block](https://www.w3.org/TR/webvtt1/#webvtt-cue-block) can include an [optional cue identifier](https://www.w3.org/TR/webvtt1/#webvtt-cue-identifier).

The vtt-files I currently want to convert with the help of this library are very close to the srt format and so use a sequence number as cue identifier already.

So looking at your code that converts the formats, I would expect this cue identifier to get handled (removed) to create a valid conversion.

## Current Behavior
When I try to convert those numbered cues, I end up with a doubled numbering in consecutive lines before each timestamp.
This is, because you do not look for cue identifiers and remove them in the current version of this library.
Sequence numbers are added in any case and so you end up with a doubled numbering.

## Possible Solution
As the conversion in this library is mostly done by several direct replacements on the file contents instead of parsing the full vtt content first, it is not easy to modify it and drop any possibly detected cue identifier lines.
So I modified the function [add_sequence_numbers](https://github.com/jsonzilla/vtt_to_srt3/blob/672450c158e6f25e6231f10b32a86ccc98d78c08/vtt_to_srt/vtt_to_srt.py#L77) to drop any non-empty lines before a line with a timestamp.
It's not a very elegant solution, but it works and doesn't need a complex redesign of the input handling in [convert_content](https://github.com/jsonzilla/vtt_to_srt3/blob/672450c158e6f25e6231f10b32a86ccc98d78c08/vtt_to_srt/vtt_to_srt.py#L53).

## Steps to Reproduce
1. Download example file 'E1x1_en.vtt.txt' from attachments and rename it to .vtt
2. Convert the single file with the following code snippet
```
import vtt_to_srt.vtt_to_srt as vtt_to_srt
vtt_file = vtt_to_srt.ConvertFile('E1x1_en.vtt', 'utf-8')
vtt_file.convert()
```
3. Check created srt-file for double numbering in front of any cue block

## Context (Environment)
* **Version**: vtt_to_srt3-0.2.0.0-py3-none-any.whl
* **Platform**: Windows 64-bit, Python 3.7-32bit
* **Subsystem**: -
* **Files**: vtt_to_srt.py

## Detailed Description
see above

## Possible Implementation

```
    def add_sequence_numbers(self, contents):
        """Adds sequence numbers to subtitle contents and returns new subtitle contents

        :contents -- contents of vtt file
        """
        output = ''
        lines = contents.split('\n')
        i = 1
        n = 0
        while n < len(lines)-1:
            line = lines[n]
            next_line = lines[n+1]
            if self.has_timestamp(next_line):
                if line == '':
                    output += '\n'
                output += str(i) + '\n'
                output += next_line + '\n'
                i += 1
                n += 2
            else:
                output += line + '\n'
                n += 1
        output += lines[-1] + '\n'
        return output
```

[E1x1_en.vtt.txt](https://github.com/jsonzilla/vtt_to_srt3/files/10471525/E1x1_en.vtt.txt)

**Comment by jsonzilla** [comment]
First, thanks for the correct report.
Fix only works for simplest cue identifiers like numbers "1", using a regex. The convention of cue identifiers, with annotations, does not work. At the moment, this package is not a complete converter.
